### ISSUE TITLE
Transfer management api

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/management-api#2]
Let's transfer management api ( `GetStorageSlice` is an exception, it will be transferred letter) here from artipie, set up github actions, rultor and whole infrastructure and make-up readme file.

**Comment by olenagerasimova** [comment]
@yegor256 could you please touch `.rultor` here, so we could release when necessary?

**Comment by yegor256** [comment]
@olenagerasimova @olegmoz done

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.1`

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#22](https://github.com/artipie/management-api/issues/22) is still not solved.
