### ISSUE TITLE
Support .yaml and .yml extensions for config files

### ISSUE THREAD

**Issue by genryxy** [artipie/management-api#27]
Now in `artipie` module both extensions are supported (see artipie/artipie#797). There is logic based on config file extension in this repository (in `GetPermissionSlice`, `UserPage`, etc). It is necessary to move this logic from `management-api` repository by using `ConfigFile`  (or something else) from `artipie` module.

**Comment by 0pdd** [comment]
@genryxy the puzzle [#31](https://github.com/artipie/management-api/issues/31) is still not solved.

**Comment by genryxy** [comment]
@olegmoz could you please release a new version

**Comment by olegmoz** [comment]
@rultor release, tag=`0.4`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.4.1`

**Comment by 0pdd** [comment]
@genryxy the only puzzle [#31](https://github.com/artipie/management-api/issues/31) is solved here.
