### ISSUE TITLE
UpdateRepo API hangs on POST request

### ISSUE THREAD

**Issue by g4s8** [artipie/management-api#35]
The API for `POST /api/repos/` hangs infinity on requests with valid payload: URL-encoded form with `repo` and `config` parameters.

Initialize reported as https://github.com/artipie/artipie/issues/896
Reproduced with integration test: https://github.com/artipie/artipie/pull/897

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4.3`

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4.4`
